# Generated by Django 6.0 on 2025-12-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Имя'),
        ),
    ]
